spring:
  profiles:
    active: rabbit

logging:
  level:
    org: INFO

srping:
  artemis:
    mode: native
    host: localhost
    port: 9876
    user: admin
    password: admin

rabbit-client-duration: 0
artemis-broker-url: 0
jms-queue-destination: hello.queue
kafka-bootstrap-address: http://localhost:9092
