kafka:
  bootstrapAddress: http://localhost:9092

spring:
  profiles:
    active: kafka

logging:
  level:
    org: INFO

rabbit:
  client:
    duration: 100

srping:
  artemis:
    mode: native
    host: localhost
    port: 9876
    user: admin
    password: admin

jms:
  queue:
    destination: hello.queue